# Generated by Django 5.0.3 on 2024-05-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("writer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="is_premium",
            field=models.BooleanField(default=False, verbose_name="Premium article"),
        ),
    ]
